config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
    post 'calendars/destroy_user_session', as: :destroy_users_session
  end
  resources :calendars
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    def admin?
          self.admin
    end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def after_sign_in_path_for(resource)
      if resource.admin? 
        root_path
      else 
      calendars_path
      end
    end
  def configure_permitted_parameters
    # /users/sign_up
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :phone_number, :full_name])
  end


end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    @calendars = Calendar.all
    @calendar = Calendar.new
  end

  def new
    @calendar = Calendar.new
  end

  def show
    @calendar = Calendar.find(params[:id])
  end

  def create
    Calendar.create(calendar_parameter)
    redirect_to calendars_path
  end

  def destroy
    @calendar = Calendar.find(params[:id])
    @calendar.destroy
    redirect_to calendars_path, notice: "削除しました"
  end

  def edit
    @calendar = Calendar.find(params[:id])
  end
  def update
    @calendar = Calendar.find(params[:id])
    if @calendar.update(calendar_parameter)
      redirect_to calendars_path, notice: "編集しました"
    else
    render 'edit'
    end
  end

  def destroy_user_session
    reset_session
    redirect_to root
  end

  private

  def calendar_parameter
  params.require(:calendar).permit(:title, :content, :start_time)
  end

end

app/controllers/devises/confirmations_controller.rb
# frozen_string_literal: true

class Devises::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/devises/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Devises::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/devises/passwords_controller.rb
# frozen_string_literal: true

class Devises::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/devises/registrations_controller.rb
# frozen_string_literal: true

class Devises::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/devises/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
    redirect_to calendars_index_path
  end
  def user
    super
    render "calendars/index"
    # redirect_to calendars_index_path
    # root_path
  end

  # POST /resource/sign_in
  # def create
  #   super
  #   redirect_to calendars_index_path
  #   # root_path
  # end
  # root_path
  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/devises/unlocks_controller.rb
# frozen_string_literal: true

class Devises::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/turbo_devise__controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/turbo_devise__helper.rb
module TurboDeviseHelper
end

app/views/calendars/edit.html.erb
<%= form_with(model: @calendar, local: false) do |form| %>

  <div class="title">
    <div class="form-tag">タイトル</div>
    <%= form.text_field :title %>
  </div>


  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>

    <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>

<div class="toppage">
<h1 class="top">カレンダー</h1>
<br>

<div class="row">
<div class="col-md-4">
	<div class="schedule">今後の予定一覧</div>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>タイトル</th>
      <th>日程</th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.each do |calendar| %>
      <tr>
        <td><%= link_to calendar.title , calendar %></td>
        <td><%= calendar.start_time.strftime("%m-%d") %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= form_with(model: @calendar, local: false) do |form| %>

  <div class="title">
    <div class="form-tag">タイトル</div>
    <%= form.text_field :title %>
  </div>


  <div class="content">
    <div class="form-tag">内容</div>
    <%= form.text_field :content %>
  </div>

    <div class="time">
    <div class="form-tag">時間</div>
    <%= form.datetime_select :start_time %>
  </div>

 <div class="submit">
    <%= form.submit %>
 </div>
<% end %>
</div>

<br>


<br>
<div class="col-md-8">
<%= month_calendar events: @calendars do |date, calendars| %>
  <%= date.day %>

  <% calendars.each do |calendar| %>
    <div>
      <%= link_to calendar.title, calendar %>
    </div>
  <% end %>
<% end %>
</div>
</div>
</div>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
<p>
  <strong>タイトル</strong>
  <%= @calendar.title %>
</p>

<p>
  <strong>内容</strong>
  <%= @calendar.content %>
</p>

<p>
  <strong>日時</strong>
  <%= @calendar.start_time.strftime("%m-%d") %>
</p>

<%= link_to '編集', edit_calendar_path(@calendar) %>
<%= button_to '消去', calendar_path(@calendar.id), method: :delete, data: { confirm: '本当に?' } %>
<%= button_to '戻る', calendar_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
      <!--管理者権限
      <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'カレンダー管理', calendars_path %>
      <% end %> -->
      <% if user_signed_in? %>
        <li>
          <%= button_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "サインアップ", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title"> <%= start_date.year %><%= t('date.month_names')[start_date.month] %></span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title"><%= start_date.year %> <%= t('date.month_names')[start_date.month] %></time>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title">
      <%= t('simple_calendar.week', default: 'Week') %>
      <%= calendar.week_number %>
      <% if calendar.number_of_weeks > 1 %>
        - <%= calendar.end_week %>
      <% end %>
    </span>

    <nav>
      <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
    </nav>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>